#!/bin/bash
vpcm_addr=$1
baseline_addr=$2

#Building configuration loader
make -C configloader clean; make -C configloader

if [ ! -d "$GOPATH/puff" ];then
    git clone https://github.com/marxn/puff.git
fi

echo "Building puff..."
make -C puff clean; make -C puff

if [ ! -d "$GOPATH/vpcm" ];then
    if [ "$vpcm_addr" != "" ];then
        echo "Importing SCM module..."
        git clone $vpcm_addr $GOPATH/vpcm
    else
        echo "Notice: $GOPATH/vpcm directory does not exist."
    fi
fi

if [ ! -d "$GOPATH/baseline" ];then
    if [ "$baseline_addr" != "" ];then
        echo "Importing baseline..."
        git clone $baseline_addr $GOPATH/baseline
    else
        echo "Notice: $GOPATH/baseline directory does not exist."
    fi
fi

