#!/bin/bash
#Vspace Manufacture Tool
username=`id -un`
projectroot="$HOME/project"

publish_project() {
    hostname=$1
    port=$2
    username=$3
    projectname=$4
    tag=$5
    nginx_conf_path=""
    token=`cat /proc/sys/kernel/random/uuid`
    
    cp $GOPATH/deploy/*.sh $GOPATH/target/$projectname/$tag
    if [ -f $GOPATH/vpcm/project/$projectname/conf/nginx.conf ]; then
        cp $GOPATH/vpcm/project/$projectname/conf/nginx.conf $GOPATH/target/$projectname/$tag
        nginx_conf_path=`cat $GOPATH/vpcm/global/nginx_path.env`
    fi
    cd $GOPATH/target/
    tar -czf $projectname.tar.gz $projectname/$tag/
    scp -P $port -q $projectname.tar.gz $username@$hostname:$projectroot/$projectname.tar.gz
    ssh -p $port -qt $username@$hostname "cd $projectroot; tar -xf $projectroot/$projectname.tar.gz; rm -f $projectroot/$projectname.tar.gz"
    ssh -p $port -qt $username@$hostname "sudo bash $projectroot/$projectname/$tag/vasc_init.sh \"$serviceroot\" \"$serviceuser\" \"$servicegroup\" \"$projectname\" \"$tag\" \"$nginx_conf_path\" \"$environment\" \"$token\""
    
    #Compatible with rigger
    if [ -d $GOPATH/target/$projectname/$tag/_rg ]; then
        ssh -p $port -qt $username@$hostname "cd $serviceroot/$projectname;chmod +x ./bin/*.sh; ./bin/setup.sh $environment"
    fi
    rm -f $projectname.tar.gz
}

pull_branch() {
    remote=`git remote -v | grep push | awk '{print $2}'`
    current_branch=`git rev-parse --abbrev-ref HEAD`
    remote_branch=`git branch -r | grep $current_branch`
    if [ "$remote_branch" == "" ]; then
        git push origin $current_branch
    fi
    git pull $remote $current_branch
}

action=""
force_publish="no"

while [ $# -ge 1 ] ; do
    case "$1" in
        -p) baseline=$2; action=publish; shift 2;;
        -f) baseline=$2; action=publish; force_publish="yes"; shift 2;;
        -g) baseline=""; action=generate; shift 1;;
        -r) action=retrieve; if [ "$2" != "" ]; then dest_host=$2; shift 2; else shift 1; fi;;
         *) echo "unknown parameter $1." ; exit 1 ; break;;
    esac
done

if [ "$action" == "" ]; then
    echo "usage: vmt <-g -p -f -r> [<baseline/hostname>]"
    echo "Example: vmt -g [baseline]   Generate a new baseline for all projects controlled in vpcm."
    echo "Example: vmt -p <baseline>   Publish the baseline(Give options prompt when remote version is higher or equals to local)"
    echo "Example: vmt -f <baseline>   Publish the baseline by force(No prompt)"
    echo "Example: vmt -r <hostname>   Retrieve remote baseline"
    exit 1
fi

if [ ! -f $GOPATH/vpcm/global/service_root.env ]; then
        echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/global/service_root.env\033[0m"
        exit 1
fi
serviceroot=`cat $GOPATH/vpcm/global/service_root.env`
if [ "$serviceroot" == "" ]; then
    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/global/service_root.env\033[0m"
    exit 1
fi

if [ ! -f $GOPATH/vpcm/global/service_user.env ]; then
    echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/global/service_user.env\033[0m"
    exit 1
fi
serviceuser=`cat $GOPATH/vpcm/global/service_user.env`
if [ "$serviceuser" == "" ]; then
    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/global/service_user.env\033[0m"
    exit 1
fi

if [ ! -f $GOPATH/vpcm/global/service_group.env ]; then
    echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/global/service_group.env\033[0m"
    exit 1
fi
servicegroup=`cat $GOPATH/vpcm/global/service_group.env`
if [ "$servicegroup" == "" ]; then
    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/global/service_group.env\033[0m"
    exit 1
fi
if [ ! -f $GOPATH/vpcm/global/environment.env ]; then
    echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/global/environment.env\033[0m"
    exit 1
fi
environment=`cat $GOPATH/vpcm/global/environment.env`
if [ "$environment" == "" ]; then
    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/global/environment.env\033[0m"
    exit 1
fi

cwd=`pwd`

if [ "$action" == "retrieve" ]; then
    if [ "$dest_host" == "" ]; then
        dest_host=`head -n1 $GOPATH/vpcm/global/host_list.scm | sed "s/^[ \t#]*//g" | sed "s/[ \t]*$//g"`
    fi
    hostname=${dest_host%%:*}
    port=${dest_host##*:}
    ssh -p $port -qt $username@$hostname "sudo cat $serviceroot/baseline"
    exit $?
fi

if [ "$action" == "generate" ]; then
    cd $GOPATH/vpcm/
    pull_branch
    cd $cwd

    if [ "$baseline" == "" ]; then
        uuid=`cat /proc/sys/kernel/random/uuid`
        timestamp=`date -d "now" '+%Y%m%d-%H%M%S'`
        newbaseline="$username--$timestamp--$uuid"
    else
        newbaseline=$baseline
    fi
    touch $GOPATH/unstamped.txt
    while read line
    do
        projectname=${line%% *}
        address=${line##* }

        if [ "$projectname" == "" ]; then
            continue
        fi

        echo "Checking version for $projectname..."
        if [ ! -d $GOPATH/src/$projectname ]; then
            echo -e "\033[33mCannot find source code directory for project:$projectname. Try to check it out...\033[0m"
            cd $GOPATH/src
            git clone $address $projectname
            if [ "$?" != "0" ]; then
                echo -e "\033[31mCannot check out project:$projectname.\033[0m"
                exit 1
            fi
        fi
        cd $GOPATH/src/$projectname
        changed_files=`git diff --name-only`
        if [ "$changed_files" != "" ]; then
            echo -e "\033[31mProject [$projectname] has files to be commited:\n$changed_files\033[0m"
            #exit 1
        fi

        if [ ! -f "$GOPATH/src/$projectname/version.txt" ]; then
            if [ ! -f "$GOPATH/src/$projectname/src/version.txt" ]; then
                echo -e "\033[31mCannot find source code version.txt for project:$projectname\033[0m"
                exit 1
            else
                tag=`cat $GOPATH/src/$projectname/src/version.txt`
            fi
        else
            tag=`cat $GOPATH/src/$projectname/version.txt`
        fi

        if [ "$tag" == "" ]; then
            echo -e "\033[31mEmpty version.txt for project:$projectname\033[0m"
            exit 1
        fi

        unstamped=`git diff --stat $tag HEAD`
        if [ "$unstamped" != "" ]; then
            echo "$projectname" >> $GOPATH/unstamped.txt
        fi
        echo "$projectname/$tag" >> $GOPATH/baseline/$newbaseline
    done < $GOPATH/vpcm/global/project_list.scm

    unstamped_project=`cat $GOPATH/unstamped.txt`
    rm -f $GOPATH/unstamped.txt
    if [ "$unstamped_project" != "" ]; then
        echo -e "\033[33mFollowing project(s) seems do not have a new version since last modification:\n$unstamped_project\033[0m"
        read -p "Do you insist to continue?(yes/no):" iscontinue
        if [ "$iscontinue" != "yes" ]; then
            rm -f $GOPATH/baseline/$newbaseline
            exit 1
        fi
    fi

    echo -e "\033[32mGenerating new baseline successfully.\nNew baseline: $newbaseline\033[0m"
    read -p "Do you want to commit this baseline?(yes/no):" commit
    if [ "$commit" == "yes" ]; then
        cd $GOPATH/baseline/
        git add $newbaseline
        git commit -m "$newbaseline"
        git push
        cd $cwd
    fi
fi

if [ "$action" == "publish" ]; then
    has_published_project="0"
    if [ "$baseline" == "" ]; then
        echo -e "Baseline must be identified"
        exit 1
    fi

    cd $GOPATH/vpcm
    pull_branch
    cd $GOPATH/baseline
    git pull
    cd $cwd

    #Check projects in target directory. build if it does not exist
    baselines=`cat $GOPATH/baseline/$baseline`
    for line in $baselines
    do
        tag=${line##*/}
        projectname=${line%%/*}
        packagepath=$GOPATH/target/$projectname/$tag
        if [ ! -d "$packagepath" ]; then
            $GOPATH/vbuild -p $projectname -t $tag
            if [ "$?" != "0" ]; then
                echo -e "\033[31mCannot build $projectname/$tag.\033[0m"
                exit 1
            fi
        fi
    done
    
    hostlist=`cat $GOPATH/vpcm/global/host_list.scm`
    for hostline in $hostlist
    do
        hostname=${hostline%%:*}
        port=${hostline##*:}
        echo "Checking $hostname:$port..."
        ssh -p $port -tq $username@$hostname "mkdir -p $projectroot"
        ssh -p $port -tq $username@$hostname "sudo cp -f $serviceroot/baseline $projectroot/baseline"
        scp -P $port -q  $username@$hostname:$projectroot/baseline /tmp/baseline.$hostname
        ssh -p $port -tq $username@$hostname "sudo rm -f $projectroot/baseline"

        if [ ! -f /tmp/baseline.$hostname ]; then
            echo -e "\033[33mCannot fetch remote baseline for host:$hostname Attempt to launch force publishing...\033[0m"
            force_publish="yes"
        fi

        rm -f "/tmp/final_baseline.$hostname"
        touch "/tmp/final_baseline.$hostname"
        for line in $baselines
        do
            tag=${line##*/}
            projectname=${line%%/*}
            if [ "$force_publish" == "yes" ]; then
                echo -e "\033[33mForce publishing $projectname: $tag\033[0m"
                publish_project $hostname $port $username $projectname $tag
                echo $line >> /tmp/final_baseline.$hostname
                has_published_project="1"
            else
                remoteitem=`grep -E "^$projectname/" /tmp/baseline.$hostname`
                remotetag=${remoteitem##*/}
                compare=`checkver $tag $remotetag`
                if [ "$compare" == "1" ]; then
                    echo -e "\033[33m$projectname: $remotetag -> $tag\033[0m"
                    publish_project $hostname $port $username $projectname $tag
                    echo $line >> /tmp/final_baseline.$hostname
                    has_published_project="1"
                else
                    echo $remoteitem >> /tmp/final_baseline.$hostname
                fi
            fi
        done
        cd $cwd
        scp -P $port -q /tmp/final_baseline.$hostname $username@$hostname:$projectroot/baseline
        ssh -p $port -tq $username@$hostname "sudo mv -f $projectroot/baseline $serviceroot; sudo chown $serviceuser:$servicegroup $serviceroot/baseline"
        if [ "$has_published_project" == "1" ]; then
            ssh -p $port -tq $username@$hostname "sudo /sbin/service nginx restart"
        fi
        rm -f /tmp/baseline.$hostname
    done
    echo -e "\033[32mPublishing finished.\033[0m"
fi

