#!/bin/bash
#Vspace Manufacture Tool
username=`id -un`
projectroot="$HOME/project"
marapubpath="/data/x/tools/mara-pub"
token=`cat /proc/sys/kernel/random/uuid`

publish_project() {
    hostname=$1
    port=$2
    username=$3
    projectname=$4
    planname=$5
    tag=$6
    nginx_conf_path=""
    
    cp $GOPATH/deploy/*.sh $GOPATH/target/$projectname/$tag
    if [ -f $GOPATH/vpcm/project/$projectname/conf/nginx.conf ]; then
        cp $GOPATH/vpcm/project/$projectname/conf/nginx.conf $GOPATH/target/$projectname/$tag
        nginx_conf_path=`cat $GOPATH/vpcm/project/$projectname/conf/nginx_path.env`
    fi
    
    if [ -d $GOPATH/target/$projectname/$tag/bin ]; then
        chmod +x $GOPATH/target/$projectname/$tag/bin/*
    fi
    
    local_serviceroot=""
    local_serviceuser=""
    local_servicegroup=""
    
    if [ -f $GOPATH/vpcm/project/$projectname/conf/service_root.env ]; then 
        local_serviceroot=`cat $GOPATH/vpcm/project/$projectname/publish/$planname.service_root` 
    fi
    if [ -f $GOPATH/vpcm/project/$projectname/conf/service_user.env ]; then 
        local_serviceuser=`cat $GOPATH/vpcm/project/$projectname/publish/service_user.env`
    fi
    if [ -f $GOPATH/vpcm/project/$projectname/conf/service_group.env ]; then 
        local_servicegroup=`cat $GOPATH/vpcm/project/$projectname/publish/service_group.env`
    fi
    
    if [ "$local_serviceuser" == "" ]; then
        local_serviceuser=$serviceuser
    fi
    if [ "$local_servicegroup" == "" ]; then
        local_servicegroup=$servicegroup
    fi
    if [ "$local_serviceroot" == "" ]; then
        local_serviceroot=`publoader -e $environment -i $marapubpath -p $planname -s deploy`
    fi

    cd $GOPATH/target/
    tar -czf $projectname.tar.gz $projectname/$tag/
    
    scp -P $port -q $projectname.tar.gz $username@$hostname:$projectroot/$projectname.tar.gz
    ssh -p $port -qt $username@$hostname "cd $projectroot; tar -xf $projectroot/$projectname.tar.gz; rm -f $projectroot/$projectname.tar.gz"
    
    if [ -f $GOPATH/vpcm/project/$projectname/publish/$planname.before ]; then
        before_cmd=`cat $GOPATH/vpcm/project/$projectname/publish/$planname.before`
    else
        before_cmd=`publoader -e $environment -i /data/x/tools/mara-pub -p $planname -s before`
    fi
    
    if [ -f $GOPATH/vpcm/project/$projectname/publish/$planname.after ]; then
        after_cmd=`cat $GOPATH/vpcm/project/$projectname/publish/$planname.after`
    else
        after_cmd=`publoader -e $environment -i /data/x/tools/mara-pub -p $planname -s after`
    fi
    
    export_path=`publoader -e $environment -i $marapubpath -p $planname -s exportpath`
    
    #Before publishing, do something compliable with rigger
    if [ "$before_cmd" != "" ]; then
        echo "Calling $projectname - $planname - before: [$before_cmd]"
        ssh -p $port -qt $username@$hostname "if [ -d $local_serviceroot/$projectname ]; then cd $local_serviceroot/$projectname; sudo $before_cmd; fi"
    fi
    
    #Do publishing
    ssh -p $port -qt $username@$hostname "sudo bash $projectroot/$projectname/$tag/vasc_init.sh \"$local_serviceroot\" \"$local_serviceuser\" \"$local_servicegroup\" \"$projectname\" \"$export_path\" \"$tag\" \"$nginx_conf_path\" \"$environment\" \"$token\""
    
    #After publishing, compatible with rigger
    if [ "$after_cmd" != "" ]; then
        echo "Calling $projectname - $planname - after: [$after_cmd]"
        ssh -p $port -qt $username@$hostname "cd $local_serviceroot/$projectname; sudo $after_cmd"
    fi
    rm -f $projectname.tar.gz
}

pull_branch() {
    branch=$1
    remote=`git remote -v | grep push | awk '{print $2}'`
    
    if [ "$branch" != "" ]; then
        git checkout $branch
    fi
    
    current_branch=`git rev-parse --abbrev-ref HEAD`
    remote_branch=`git branch -r | grep $current_branch`
    if [ "$remote_branch" == "" ]; then
        git push origin $current_branch
    fi
    git pull $remote $current_branch
    git fetch --tags
}

action=""
publish_option="no"
pull_source="no"

while [ $# -ge 1 ] ; do
    case "$1" in
        -p) baseline=$2; action=publish; publish_option="upgrade";shift 2;;
        -d) baseline=$2; action=publish; publish_option="diff"; shift 2;;
        -f) baseline=$2; action=publish; publish_option="all"; shift 2;;
        -g) baseline=""; action=generate; shift 1;;
        -c) baseline=""; action=generate; pull_source="yes"; shift 1;;
        -r) action=retrieve; if [ "$2" != "" ]; then dest_host=$2; shift 2; else shift 1; fi;;
         *) echo "unknown parameter $1." ; exit 1 ; break;;
    esac
done

if [ "$action" == "" ]; then
    echo "usage: vmt <-g -p -f -r> [<baseline/hostname>]"
    echo "Example: vmt -g              Generate a new baseline for all projects controlled in vpcm.(Do not pull)"
    echo "Example: vmt -c              Create a new baseline for all projects controlled in vpcm.(Pull from master)"
    echo "Example: vmt -p <baseline>   Publish the baseline(Only publish projects whose version is higher than remote)"
    echo "Example: vmt -d <baseline>   Publish the baseline(Only publish projects whose version is different from remote)"
    echo "Example: vmt -f <baseline>   Publish all the projects in baseline by force"
    echo "Example: vmt -r [<hostname>] Retrieve remote baseline from first host"
    exit 1
fi

if [ ! -f $GOPATH/vpcm/global/service_root.env ]; then
        echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/global/service_root.env\033[0m"
        exit 1
fi
serviceroot=`cat $GOPATH/vpcm/global/service_root.env`
if [ "$serviceroot" == "" ]; then
    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/global/service_root.env\033[0m"
    exit 1
fi

if [ ! -f $GOPATH/vpcm/global/service_user.env ]; then
    echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/global/service_user.env\033[0m"
    exit 1
fi
serviceuser=`cat $GOPATH/vpcm/global/service_user.env`
if [ "$serviceuser" == "" ]; then
    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/global/service_user.env\033[0m"
    exit 1
fi

if [ ! -f $GOPATH/vpcm/global/service_group.env ]; then
    echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/global/service_group.env\033[0m"
    exit 1
fi
servicegroup=`cat $GOPATH/vpcm/global/service_group.env`
if [ "$servicegroup" == "" ]; then
    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/global/service_group.env\033[0m"
    exit 1
fi
if [ ! -f $GOPATH/vpcm/global/environment.env ]; then
    echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/global/environment.env\033[0m"
    exit 1
fi
environment=`cat $GOPATH/vpcm/global/environment.env`
if [ "$environment" == "" ]; then
    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/global/environment.env\033[0m"
    exit 1
fi

cwd=`pwd`

if [ "$action" == "retrieve" ]; then
    if [ "$dest_host" == "" ]; then
        dest_host=`head -n1 $GOPATH/vpcm/global/host_list.scm | sed "s/^[ \t#]*//g" | sed "s/[ \t]*$//g"`
    fi
    hostname=${dest_host%%:*}
    port=${dest_host##*:}
    ssh -p $port -qt $username@$hostname "sudo cat $serviceroot/baseline"
    exit $?
fi

if [ "$action" == "generate" ]; then
    cd $GOPATH/vpcm/
    pull_branch
    cd $cwd

    if [ "$baseline" == "" ]; then
        uuid=`cat /proc/sys/kernel/random/uuid`
        timestamp=`date -d "now" '+%Y%m%d-%H%M%S'`
        newbaseline="$username--$timestamp--$uuid"
    else
        newbaseline=$baseline
    fi
    touch $GOPATH/unstamped.txt
    while read line
    do
        projectname=`echo $line | awk '{ print $1; }'`
        address=`echo $line | awk '{ print $2; }'`
        need_included_baseline=`echo $line | awk '{ print $3; }'`
        
        if [ "$projectname" == "" ]; then
            continue
        fi
        if [ "$need_included_baseline" != "yes" ]; then
            continue
        fi
        
        echo "Checking version for $projectname..."
        if [ ! -d $GOPATH/src/$projectname ]; then
            echo -e "\033[33mCannot find source code directory for project:$projectname. Try to check it out...\033[0m"
            cd $GOPATH/src
            git clone $address $projectname
            if [ "$?" != "0" ]; then
                echo -e "\033[31mCannot check out project:$projectname.\033[0m"
                exit 1
            fi
        fi
        cd $GOPATH/src/$projectname
        if [ "$pull_source" == "yes" ]; then
            pull_branch "master"
        else
            git fetch --tags
        fi
        changed_files=`git diff --name-only`
        if [ "$changed_files" != "" ]; then
            echo -e "\033[31mProject [$projectname] has files to be commited:\n$changed_files\033[0m"
            exit 1
        fi
        
        if [ ! -f "$GOPATH/src/$projectname/version.txt" ]; then
            if [ ! -f "$GOPATH/src/$projectname/src/version.txt" ]; then
                echo -e "\033[31mCannot find version.txt for project:$projectname\033[0m"
                continue
            else
                tag=`cat $GOPATH/src/$projectname/src/version.txt`
            fi
        else
            tag=`cat $GOPATH/src/$projectname/version.txt`
        fi

        if [ "$tag" == "" ]; then
            echo -e "\033[31mEmpty version.txt for project:$projectname\033[0m"
            exit 1
        fi
        unstamped=`git diff --stat $tag HEAD`
        if [ "$unstamped" != "" ]; then
            echo "$projectname" >> $GOPATH/unstamped.txt
        fi
        echo "$projectname/$tag" >> $GOPATH/baseline/$newbaseline
    done < $GOPATH/vpcm/project_list.scm

    unstamped_project=`cat $GOPATH/unstamped.txt`
    rm -f $GOPATH/unstamped.txt
    if [ "$unstamped_project" != "" ]; then
        echo -e "\033[33mFollowing project(s) seems do not have a new tag since last modification:\n$unstamped_project\033[0m"
        read -p "Do you want to continue?(yes/no):" iscontinue
        if [ "$iscontinue" != "yes" ]; then
            rm -f $GOPATH/baseline/$newbaseline
            exit 1
        fi
    fi

    echo -e "\033[32mGenerating new baseline successfully.\nNew baseline: \n$newbaseline\033[0m"
    read -p "Do you want to commit this baseline?(yes/no):" commit
    if [ "$commit" == "yes" ]; then
        cd $GOPATH/baseline/
        git add $newbaseline
        git commit -m "$newbaseline"
        git push
        cd $cwd
    fi
fi

if [ "$action" == "publish" ]; then
    has_published_project="0"
    if [ "$baseline" == "" ]; then
        echo -e "\033[31mBaseline cannot be empty!\033[0m"
        exit 1
    fi

    cd $GOPATH/vpcm
    pull_branch
    cd $GOPATH/baseline
    pull_branch
    cd $cwd

    #Check projects in target directory. build if it does not exist
    baselines=`cat $GOPATH/baseline/$baseline`
    for line in $baselines
    do
        tag=${line##*/}
        projectname=${line%%/*}
        packagepath=$GOPATH/target/$projectname/$tag
        if [ ! -d "$packagepath" ]; then
            $GOPATH/vbuild -p $projectname -t $tag
            if [ "$?" != "0" ]; then
                echo -e "\033[31mCannot build $projectname/$tag.\033[0m"
                exit 1
            fi
        fi
    done
    
    hostlist=`cat $GOPATH/vpcm/global/host_list.scm`
    for hostline in $hostlist
    do
        hostname=${hostline%%:*}
        port=${hostline##*:}
        echo "Checking $hostname:$port..."
        locked=`ssh -p $port -tq $username@$hostname "if [ ! -f $serviceroot/publish.lock ]; then touch $serviceroot/publish.lock; echo \"locked\" ; fi"`
        if [ "$locked" == "" ]; then
            echo -e "\033[31mPublishing failed: Someone is doing the publish on the target server. Try publishing later.\033[0m"
            exit 1
        fi
        ssh -p $port -tq $username@$hostname "mkdir -p $projectroot"
        ssh -p $port -tq $username@$hostname "sudo cp -f $serviceroot/baseline $projectroot/baseline"
        scp -P $port -q  $username@$hostname:$projectroot/baseline $GOPATH/baseline.$hostname
        ssh -p $port -tq $username@$hostname "sudo rm -f $projectroot/baseline"

        if [ ! -f $GOPATH/baseline.$hostname ]; then
            echo -e "\033[33mCannot fetch remote baseline for host:$hostname Attempt to launch force publishing...\033[0m"
            publish_option="all"
        fi

        rm -f "$GOPATH/final_baseline.$hostname"
        touch "$GOPATH/final_baseline.$hostname"
        for line in $baselines
        do
            tag=${line##*/}
            projectname=${line%%/*}
            compare="0"
            
            need_publish=`grep -E "^$projectname " $GOPATH/vpcm/project_list.scm | awk '{ print $4; }'`
            if [ "$need_publish" != "yes" ]; then
                continue
            fi
            if [ -f $GOPATH/vpcm/project/$projectname/conf/host_list.scm ]; then
                target_host=`grep "$hostline" $GOPATH/vpcm/project/$projectname/conf/host_list.scm`
                if [ "$target_host" == "" ]; then
                    echo -e "\033[33mProject $projectname does not need to be published in host $hostline.\033[0m"
                    continue
                fi
            fi
            if [ "$publish_option" == "all" ]; then
                echo -e "\033[33mForce publishing $projectname: $tag\033[0m"
                if [ ! -f $GOPATH/vpcm/project/$projectname/publish/plan_list.scm ]; then
                    echo -e "\033[31mCannot find $GOPATH/vpcm/project/$projectname/publish/plan_list.scm\033[0m"
                    continue
                fi
                plan_list=`cat $GOPATH/vpcm/project/$projectname/publish/plan_list.scm`
                if [ "$plan_list" == "" ]; then
                    echo -e "\033[31mCannot find any content in $GOPATH/vpcm/project/$projectname/publish/plan_list.scm\033[0m"
                    continue
                fi
                for planname in $plan_list
                do
                    target_plan_host=`grep $hostline $GOPATH/vpcm/project/$projectname/publish/$planname.host`
                    if [ "$target_plan_host" != "" ]; then
                        publish_project $hostname $port $username $projectname $planname $tag
                        echo $line >> $GOPATH/final_baseline.$hostname
                        has_published_project="1"
                    fi
                done
            else
                remoteitem=`grep -E "^$projectname/" $GOPATH/baseline.$hostname`
                if [ "$remoteitem" != "" ]; then
                    remotetag=${remoteitem##*/}
                     
                    if [ "$publish_option" == "diff" ]; then
                        if [ "$tag" != "$remotetag" ]; then
                            compare="1"
                        fi
                    else
                        if [ "$publish_option" == "upgrade" ]; then
                            compare=`checkver "$tag" "$remotetag"`
                        fi
                    fi
                else
                    remotetag=""
                    compare="1"
                fi
                if [ "$compare" == "1" ]; then
                    echo -e "\033[33m$projectname: $remotetag -> $tag\033[0m"
                    if [ ! -f $GOPATH/vpcm/project/$projectname/publish/plan_list.scm ]; then
                        echo -e "\033[33mCannot find $GOPATH/vpcm/project/$projectname/publish/plan_list.scm.\033[0m"
                        continue
                    fi
                    plan_list=`cat $GOPATH/vpcm/project/$projectname/publish/plan_list.scm`
                    if [ "$plan_list" == "" ]; then
                        echo -e "\033[33mCannot find any content in $GOPATH/vpcm/project/$projectname/publish/plan_list.scm.\033[0m"
                        continue
                    fi
                    for planname in $plan_list
                    do
                        target_plan_host=`grep $hostline $GOPATH/vpcm/project/$projectname/publish/$planname.host`
                        if [ "$target_plan_host" != "" ]; then
                            publish_project $hostname $port $username $projectname $planname $tag
                            echo $line >> $GOPATH/final_baseline.$hostname
                            has_published_project="1"
                        fi
                    done
                else
                    echo -e "\033[33mSkip $projectname for lower version detected.\033[0m"
                    if [ "$remoteitem" != "" ]; then
                        echo $remoteitem >> $GOPATH/final_baseline.$hostname
                    fi
                fi
            fi
        done

        if [ "$has_published_project" == "1" ]; then
            echo "Merging baseline..."
            mergebaseline $GOPATH/baseline.$hostname $GOPATH/final_baseline.$hostname
            echo "Uploading baseline..."
            scp -P $port -q $GOPATH/baseline.$hostname $username@$hostname:$projectroot/baseline
            echo "Updating baseline"
            ssh -p $port -tq $username@$hostname "sudo mv -f $projectroot/baseline $serviceroot; sudo chown $serviceuser:$servicegroup $serviceroot/baseline"
            ssh -p $port -tq $username@$hostname "sudo /sbin/service nginx restart"
        fi
        ssh -p $port -tq $username@$hostname "rm -f $serviceroot/publish.lock"
        rm -f $GOPATH/baseline.$hostname
        rm -f $GOPATH/final_baseline.$hostname
    done
    echo -e "\033[32mPublishing finished.\033[0m"
fi

