#!/bin/bash
timestamp=`date -d "now" '+%Y%m%d-%H%M%S'`
cp /data/x/baseline /data/x/baseline.$timestamp
$GOPATH/tools/fetchlocal | grep -v '^$' > /data/x/baseline
hasupdate=`diff /data/x/baseline /data/x/baseline.$timestamp`
if [ "$hasupdate" == "" ];then
    rm -f /data/x/baseline.$timestamp
else
    mv -f /data/x/baseline.$timestamp /data/x/pub_log/baseline.$timestamp
fi

