#!/bin/bash
#Vspace Manufacture Tool
username=`id -un`
projectroot="/home/$username/project"
vpcmpath="$GOPATH/vpcm"
token=`uuidgen`
toberestarted_plans=""
is_restartting="no"

checkver() {
    first=$1
    second=$2

    segs=(${first//./ })
    if [ ${#segs[@]} -ne 4 ]; then
        echo -e "Invalid version format"
        exit 1
    fi

    primary1=${segs[0]}
    secondary1=${segs[1]}
    patch1=${segs[2]}
    build1=${segs[3]}

    upgrade=(${second//./ })
    if [ ${#upgrade[@]} -ne 4 ]; then
        return 1
    fi

    primary2=${upgrade[0]}
    secondary2=${upgrade[1]}
    patch2=${upgrade[2]}
    build2=${upgrade[3]}

    if [ $primary1 -gt $primary2 ]; then
        return 1
    else
        if [ $primary1 -eq $primary2 ]; then
            if [ $secondary1 -gt $secondary2 ]; then
                return 1
            else
                if [ $secondary1 -eq $secondary2 ]; then
                    if [ $patch1 -gt $patch2 ]; then
                        return 1
                    else
                        if [ $patch1 -eq $patch2 ]; then
                            if [ $build1 -gt $build2 ]; then
                                return 1
                            fi
                        fi
                    fi
                fi
            fi
        fi
    fi

    return 0
}

publish_project() {
    hostname=$1
    port=$2
    username=$3
    projectname=$4
    planname=$5
    tag=$6
    
    if [ "$is_restartting" == "no" ];then
        cd $GOPATH/target/$destnation
        tar -czf $projectname.tar.gz $projectname/$tag/
        scp -P $port -q $projectname.tar.gz $username@$hostname:$projectroot/$projectname.tar.gz
        ssh -p $port -qt $username@$hostname "cd $projectroot; tar -xf $projectroot/$projectname.tar.gz; rm -f $projectroot/$projectname.tar.gz"
    fi

    if [ -f $vpcmpath/$destnation/config.json ]; then
        local_serviceroot=`configloader -i $vpcmpath/$destnation/config.json -p $projectname -s deploy`
        local_servicegroup=`configloader -i $vpcmpath/$destnation/config.json -p $projectname -s service_group`
        local_serviceuser=`configloader -i $vpcmpath/$destnation/config.json -p $projectname -s service_user`
        before_cmd=`configloader -i $vpcmpath/$destnation/config.json -p $projectname -s before`
        after_cmd=`configloader -i $vpcmpath/$destnation/config.json -p $projectname -s after`
        related_plan=`configloader -i $vpcmpath/$destnation/config.json -p $projectname -s related_project`
    else
        echo -e "\033[31mPublish project failed: Cannot find $vpcmpath/$destnation/config.json\033[0m"
        exit 1
    fi

    if [ "$before_cmd" != "" ]; then
        echo "Calling $projectname - $planname - before: [$before_cmd]"
        ssh -p $port -qt $username@$hostname "if [ -d $local_serviceroot/$projectname ]; then cd $local_serviceroot/$projectname; sudo $before_cmd; fi"
    fi

    if [ "$is_restartting" == "no" ];then
        #Do publishing
        nginx_addr=`configloader -i $vpcmpath/$destnation/config.json -s nginx_addr`
        ssh -p $port -qt $username@$hostname "sudo bash $projectroot/$projectname/$tag/vasc_init.sh \"$local_serviceroot\" \"$local_serviceuser\" \"$local_servicegroup\" \"$projectname\" \"$export_path\" \"$tag\" \"$environment\" \"$token\" \"$nginx_addr\""
        toberestarted_plans="$toberestarted_plans $related_plan"
    fi
   
    if [ "$after_cmd" != "" ]; then
        echo "Calling $projectname - $planname - after: [$after_cmd]"
        ssh -p $port -qt $username@$hostname "cd $local_serviceroot/$projectname; sudo $after_cmd"
    fi
    
    rm -f $projectname.tar.gz
}

restart_plan() {
    hostname=$1
    port=$2
    username=$3
    
    #Restart related projects
    is_restartting="yes"
    if [ "$toberestarted_plans" != "" ];then
        for related_plan in $toberestarted_plans
        do
            echo -e "\033[35mRestarting $related_plan...\033[0m"
            related_project = related_plan
            if [ "$related_project" @= "" ];then
                publish_project $hostname $port $username $related_project $related_plan
            fi
        done
    fi
    is_restartting="no"
}

pull_branch() {
    branch=$1
    remote=`git remote -v | grep push | awk '{print $2}'`
    
    if [ "$branch" != "" ]; then
        git checkout $branch
    fi
    
    current_branch=`git rev-parse --abbrev-ref HEAD`
    remote_branch=`git branch -r | grep $current_branch`
    if [ "$remote_branch" == "" ]; then
        git push origin $current_branch
    fi
    git pull $remote $current_branch
    git fetch --tags
}

mergebaseline() {
    old_baseline=$1
    new_baseline=$2
    old_baseline_items=`cat $old_baseline`
    for line in $old_baseline_items
    do
        tag=${line##*/}
        projectname=${line%%/*}
        project_posttion=`grep -n $projectname $new_baseline`
        if [ "$project_posttion" == "" ]; then
            echo $line >> $new_baseline
        fi
    done
}

action=""
publish_option="no"
pull_source="no"
interact_option=""

while [ $# -ge 1 ] ; do
    case "$1" in
        -e) destnation=$2; shift 2;;
        -yes) interact_option="yes"; shift 1;;
        -no) interact_option="no"; shift 1;;
        -pro) action=pubproject; shift 1;;
        -plan) action=pubproject; selected_plan=$2; shift 2;;
        -p) baseline=$2; action=publish; publish_option="upgrade";shift 2;;
        -d) baseline=$2; action=publish; publish_option="diff"; shift 2;;
        -f) baseline=$2; action=publish; publish_option="all"; shift 2;;
        -g) baseline=""; action=generate; shift 1;;
        -c) baseline=""; action=generate; pull_source="yes"; shift 1;;
        -n) baseline=$2; shift 2;;
        -u) username=$2; projectroot="/home/$username/project"; shift 2;;
         *) echo "unknown parameter $1." ; exit 1 ; break;;
    esac
done

if [ "$action" == "" ]; then
    echo " usage: vmt -g/-c -e <environment> [-n <baseline>] [-yes/-no]"
    echo " usage: vmt -p/-d/-f <baseline> -e <environment> -u <username>"
    echo " usage: vmt <-pro/-plan> -e <environment>"
    echo " Example: vmt -pro -e <environment>              Publish project in current directory to destnation environment(including all plans)"
    echo " Example: vmt -plan -e <environment>             Publish project in current directory to destnation environment(only publish identified plan)"
    echo " Example: vmt -g [-n <baseline>]                 Create a new baseline for all projects controlled in vpcm.(using current branch)"
    echo " Example: vmt -c [-n <baseline>]                 Create a new baseline for all projects controlled in vpcm.(using default branch)"
    echo " Example: vmt -p <baseline> -e <environment>     Publish the baseline(Only publish projects whose version is higher than remote)"
    echo " Example: vmt -d <baseline> -e <environment>     Publish the baseline(Only publish projects whose version is different from remote)"
    echo " Example: vmt -f <baseline> -e <environment>     Publish all the projects in baseline by force ignoring remote version"
    exit 1
fi

if [ "$destnation" == "" ]; then
    echo -e "\033[31mFailed: environment cannot be empty\033[0m"
    exit 1   
fi

environment=$destnation
serviceroot=`configloader -i $GOPATH/vpcm/$destnation/config.json -s service_root`
cwd=`pwd`
tmpfile="/tmp/$destnation-`uuidgen`.txt"

#generate a tmep file to hold project list
configloader -i $GOPATH/vpcm/$destnation/config.json -s projectlist > $tmpfile

if [ "$action" == "generate" ]; then
    cd $GOPATH/vpcm/
    pull_branch
    cd $cwd

    if [ "$baseline" == "" ]; then
        uuid=`uuidgen`
        timestamp=`date '+%Y%m%d-%H%M%S'`
        newbaseline="$timestamp--$uuid"
    else
        newbaseline=$baseline
    fi
    touch $GOPATH/unstamped.txt
    
    while read line
    do
        projectname=`echo $line | awk '{ print $1; }'`
        address=`echo $line | awk '{ print $2; }'`
        need_included_baseline=`echo $line | awk '{ print $3; }'`
        need_publish=`echo $line | awk '{ print $4; }'`
        plan_list=`echo $line | awk '{ print $5; }'`
        default_branch=`echo $line | awk '{ print $6; }'`
        
        if [ "$projectname" == "" ]; then
            continue
        fi
        if [ "$need_included_baseline" != "yes" ]; then
            continue
        fi
        
        echo "Checking version for $projectname..."
        if [ ! -d $GOPATH/src/$projectname ]; then
            echo -e "\033[33mCannot find source code directory for project:$projectname. Try to check it out...\033[0m"
            cd $GOPATH/src
            git clone $address $projectname
            if [ "$?" != "0" ]; then
                echo -e "\033[31mCannot check out project:$projectname.\033[0m"
                exit 1
            fi
        fi
        
        if [ "$default_branch" == "" ];then
            default_branch="master"
        fi
        cd $GOPATH/src/$projectname
        if [ "$pull_source" == "yes" ]; then
            pull_branch "$default_branch"
        else
            git fetch --tags
        fi
        changed_files=`git diff --name-only`
        if [ "$changed_files" != "" ]; then
            echo -e "\033[31mProject [$projectname] has files to be commited:\n$changed_files\033[0m"
            exit 1
        fi
        
        if [ ! -f "$GOPATH/src/$projectname/version.txt" ]; then
            if [ ! -f "$GOPATH/src/$projectname/src/version.txt" ]; then
                if [ ! -f "$GOPATH/src/$projectname/bin/version.txt" ]; then
                    echo -e "\033[31mCannot find version.txt for project:$projectname\033[0m"
                    continue
                else
                    tag=`cat $GOPATH/src/$projectname/bin/version.txt`
                fi
            else
                tag=`cat $GOPATH/src/$projectname/src/version.txt`
            fi
        else
            tag=`cat $GOPATH/src/$projectname/version.txt`
        fi

        if [ "$tag" == "" ]; then
            echo -e "\033[31mEmpty version.txt for project:$projectname\033[0m"
            exit 1
        fi
        unstamped=`git diff --stat $tag HEAD`
        if [ "$unstamped" != "" ]; then
            echo "$projectname" >> $GOPATH/unstamped.txt
        fi
        echo "$projectname/$tag" >> $GOPATH/baseline/$newbaseline
    done < $tmpfile

    unstamped_project=`cat $GOPATH/unstamped.txt`
    rm -f $GOPATH/unstamped.txt
    if [ "$unstamped_project" != "" ]; then
        echo -e "\033[33mFollowing project(s) seems do not have a new tag since last modification:\n$unstamped_project\033[0m"
    fi

    echo -e "\033[32mGenerating new baseline successfully.\nNew baseline: \n$newbaseline\033[0m"
    if [ "$interact_option" == "" ]; then
        read -p "Do you want to commit this baseline?(yes/no):" commit
    else
        commit=$interact_option
    fi
    
    if [ "$commit" == "yes" ]; then
        cd $GOPATH/baseline/
        git add $newbaseline
        git commit -m "$newbaseline"
        git push
        cd $cwd
    fi
fi

if [ "$action" == "pubproject" ]; then
    projectname=`basename \`pwd\``
    
    project_exist=`grep -E "^$projectname " $tmpfile`
    if [ "$project_exist" == "" ]; then
        echo -e "\033[31mCannot find $projectname in project list!\033[0m"
        exit 1
    fi
    
    if [ ! -f "$GOPATH/src/$projectname/version.txt" ]; then
        if [ ! -f "$GOPATH/src/$projectname/src/version.txt" ]; then
            if [ ! -f "$GOPATH/src/$projectname/bin/version.txt" ]; then
                echo -e "\033[31mCannot find version.txt for project:$projectname\033[0m"
                continue
            else
                tag=`cat $GOPATH/src/$projectname/bin/version.txt`
            fi
        else
            tag=`cat $GOPATH/src/$projectname/src/version.txt`
        fi
    else
        tag=`cat $GOPATH/src/$projectname/version.txt`
    fi
    uuid=`uuidgen`
    timestamp=`date '+%Y%m%d-%H%M%S'`
    baseline="$timestamp--$uuid-temp"
    echo -e "\033[33mGenerated a temporary baseline: $baseline\033[0m"
    echo "$projectname/$tag" > $GOPATH/baseline/$baseline
    action="publish"
    publish_option="all"
fi

if [ "$action" == "publish" ]; then    
    has_published_project="0"
    if [ "$baseline" == "" ]; then
        echo -e "\033[31mBaseline cannot be empty!\033[0m"
        exit 1
    fi

    cd $GOPATH/vpcm
    pull_branch
    cd $GOPATH/baseline
    pull_branch
    cd $cwd

    #Check projects in target directory. build if it does not exist
    baselines=`cat $GOPATH/baseline/$baseline`
    for line in $baselines
    do
        tag=${line##*/}
        projectname=${line%%/*}
        packagepath=$GOPATH/target/$destnation/$projectname/$tag
        if [ ! -d "$packagepath" ]; then
            $GOPATH/tools/vbuild -p $projectname -t $tag -e $destnation
            if [ "$?" != "0" ]; then
                echo -e "\033[31mCannot build $projectname/$tag.\033[0m"
                exit 1
            fi
        fi
    done
    
    hostlist=`configloader -i $GOPATH/vpcm/$destnation/config.json -s hostlist`
    
    for hostline in $hostlist
    do
        hostname=${hostline%%:*}
        port=${hostline##*:}
        echo "Checking $hostname:$port..."
        locked=`ssh -p $port -tq $username@$hostname "if [ ! -f $serviceroot/publish.lock ]; then touch $serviceroot/publish.lock; echo \"locked\" ; fi"`
        if [ "$locked" == "" ]; then
            echo -e "\033[31mPublishing failed: Someone is doing the publish on the target server. Try publishing later.\033[0m"
            exit 1
        fi
        ssh -p $port -tq $username@$hostname "mkdir -p $projectroot"
        ssh -p $port -tq $username@$hostname "sudo cp -f $serviceroot/baseline $projectroot/baseline"
        scp -P $port -q  $username@$hostname:$projectroot/baseline $GOPATH/baseline.$hostname
        ssh -p $port -tq $username@$hostname "sudo rm -f $projectroot/baseline"

        if [ ! -f $GOPATH/baseline.$hostname ]; then
            echo -e "\033[33mCannot fetch remote baseline for host:$hostname Attempt to launch force publishing...\033[0m"
            publish_option="all"
        fi

        rm -f "$GOPATH/final_baseline.$hostname"
        touch "$GOPATH/final_baseline.$hostname"
        for line in $baselines
        do
            tag=${line##*/}
            projectname=${line%%/*}
            compare="0"
            
            need_publish=`grep -E "^$projectname " $tmpfile | awk '{ print $4; }'`
            plan_list=`grep -E "^$projectname " $tmpfile | awk '{ print $5; }'`
            
            if [ "$need_publish" != "yes" ]; then
                continue
            fi
            
            OLD_IFS="$IFS"
            IFS=","
            arr=($plan_list)
            IFS="$OLD_IFS"
                
            if [ "$publish_option" == "all" ]; then
                echo -e "\033[33mForce publishing $projectname: $tag\033[0m"

                if [ "$plan_list" == "" ]; then
                    echo -e "\033[31mCannot find any plan for project $projectname\033[0m"
                    continue
                fi
                
                for planname in ${arr[@]}
                do
                    if [ "$selected_plan" != "" ]; then
                        if [ "$planname" != "$selected_plan" ]; then
                            continue
                        fi
                    fi
                    publish_project $hostname $port $username $projectname $planname $tag
                    echo $line >> $GOPATH/final_baseline.$hostname
                    has_published_project="1"
                done
            else
                remoteitem=`grep -E "^$projectname/" $GOPATH/baseline.$hostname`
                if [ "$remoteitem" != "" ]; then
                    remotetag=${remoteitem##*/}
                     
                    if [ "$publish_option" == "diff" ]; then
                        if [ "$tag" != "$remotetag" ]; then
                            compare="1"
                        fi
                    else
                        if [ "$publish_option" == "upgrade" ]; then
                            checkver "$tag" "$remotetag"
                            compare="$?"
                        fi
                    fi
                else
                    remotetag=""
                    compare="1"
                fi
                if [ "$compare" == "1" ]; then
                    echo -e "\033[33m$projectname: $remotetag -> $tag\033[0m"

                    for planname in ${arr[@]}
                    do
                        publish_project $hostname $port $username $projectname $planname $tag
                        echo $line >> $GOPATH/final_baseline.$hostname
                        has_published_project="1"
                    done
                else
                    echo -e "\033[33mSkip $projectname...\033[0m"
                    if [ "$remoteitem" != "" ]; then
                        echo $remoteitem >> $GOPATH/final_baseline.$hostname
                    fi
                fi
            fi
        done

        if [ "$has_published_project" == "1" ]; then
            toberestarted_plans=`echo $toberestarted_plans | sed 's/ /\n/g' | sort | uniq`
            restart_plan $hostname $port $username
            ssh -p $port -tq $username@$hostname "sudo /sbin/service nginx restart"
            echo "Merging baseline..."
            mergebaseline $GOPATH/baseline.$hostname $GOPATH/final_baseline.$hostname
            echo "Uploading baseline..."
            scp -P $port -q $GOPATH/final_baseline.$hostname $username@$hostname:$projectroot/baseline
            echo "Updating baseline"
            ssh -p $port -tq $username@$hostname "sudo mv -f $projectroot/baseline $serviceroot; sudo chown $serviceuser:$servicegroup $serviceroot/baseline"
        fi
        ssh -p $port -tq $username@$hostname "rm -f $serviceroot/publish.lock"
        rm -f $GOPATH/baseline.$hostname
        rm -f $GOPATH/final_baseline.$hostname
        toberestarted_plans=""
    done
    echo -e "\033[32mPublishing finished.\033[0m"
fi

rm -f $tmpfile
